/**
 * Shared ESLint flat-config presets for Craig-Amanda's Knack app repos (moved here from the retired
 * knack-apps-eslint-config repo). Consume as `import { ... } from "knack-functions/eslint"`, with the
 * devDependency pinned to the same tag the app loads at runtime.
 */
import { readFileSync } from "node:fs";
import globals from "globals";
import pluginJs from "@eslint/js";

/** Every global knackFunctions.js defines - generated by eslint/generate-globals.mjs, never edit by hand. */
export const knackFunctionsGlobals = JSON.parse(
    readFileSync(new URL("./knack-functions-globals.json", import.meta.url), "utf8")
);

/**
 * Globals Knack apps rely on that are NOT defined by knackFunctions.js - supplied by an app's own
 * code or loader, or by KTL. Keep this list short; anything knackFunctions.js defines is picked up
 * automatically.
 */
export const appRuntimeGlobals = {
    KnackApp: "readonly",
    KnackInitAsync: "writable",
    LazyLoad: "readonly",
    loadKtl: "readonly",
    showHideView: "readonly",
    showLoadingMessage: "readonly",
    triggerWebhook: "readonly"
};

/** Back-compat name from knack-apps-eslint-config: everything a Knack browser app can reference. */
export const sharedKnackGlobals = {
    ...knackFunctionsGlobals,
    ...appRuntimeGlobals
};

export const browserGlobals = {
    ...globals.browser,
    chrome: "readonly"
};

export const nodeGlobals = {
    ...globals.node
};

/** Globals supplied by the Google Apps Script runtime. */
export const googleAppsScriptGlobals = {
    Browser: "readonly",
    CacheService: "readonly",
    CalendarApp: "readonly",
    Charts: "readonly",
    ContentService: "readonly",
    console: "readonly",
    DriveApp: "readonly",
    FormApp: "readonly",
    GmailApp: "readonly",
    HtmlService: "readonly",
    Logger: "readonly",
    LockService: "readonly",
    PropertiesService: "readonly",
    ScriptApp: "readonly",
    Session: "readonly",
    SpreadsheetApp: "readonly",
    UrlFetchApp: "readonly",
    Utilities: "readonly"
};

/** Shared `eslint:recommended` rules, with `no-unused-vars` off for this codebase's style. */
export const recommendedRules = {
    ...pluginJs.configs.recommended,
    rules: {
        ...pluginJs.configs.recommended.rules,
        "no-unused-vars": "off"
    }
};

/**
 * A flat-config block for a Knack browser app's JS (app code running inside Knack, KTL, and the
 * shared Knack Functions bundle).
 * @param {string[]} files Glob patterns for the files this applies to.
 * @param {object} [extraGlobals] Extra app-specific globals to add on top of the shared set.
 * @param {object} [options]
 * @param {Record<string, string>} [options.knackFunctionsGlobals] Globals for the knack-functions version the
 *   app actually runs (see collectKnackFunctionsGlobals in ./generate-globals.mjs). Defaults to this tag's own.
 * @returns {object} An ESLint flat-config block.
 */
export function knackBrowserAppPreset(files, extraGlobals = {}, { knackFunctionsGlobals: runtimeGlobals = knackFunctionsGlobals } = {}) {
    return {
        files,
        languageOptions: {
            globals: {
                ...browserGlobals,
                Knack: "readonly",
                Ktl: "readonly",
                $: "readonly",
                jQuery: "readonly",
                ...runtimeGlobals,
                ...appRuntimeGlobals,
                ...extraGlobals
            }
        }
    };
}

/**
 * A flat-config block for Google Apps Script files (Sheets/Drive import-export scripts).
 * @param {string[]} files Glob patterns for the files this applies to.
 * @param {object} [extraGlobals] Extra app-specific globals to add on top of the shared set.
 * @returns {object} An ESLint flat-config block.
 */
export function googleAppsScriptPreset(files, extraGlobals = {}) {
    return {
        files,
        languageOptions: {
            globals: {
                ...googleAppsScriptGlobals,
                ...extraGlobals
            }
        }
    };
}

/**
 * A flat-config block for plain Node.js files (e.g. a Cloud Run service).
 * @param {string[]} files Glob patterns for the files this applies to.
 * @param {object} [extraGlobals] Extra app-specific globals to add on top of the shared set.
 * @returns {object} An ESLint flat-config block.
 */
export function nodePreset(files, extraGlobals = {}) {
    return {
        files,
        languageOptions: {
            globals: {
                ...nodeGlobals,
                ...extraGlobals
            }
        }
    };
}
